import Link from 'next/link'
import Image from 'next/image'

/**
 * Full blog article rendering. Tiptap HTML is dropped in via
 * dangerouslySetInnerHTML; styling for the inner elements lives in
 * globals.css under the `.blog-article` namespace.
 *
 * Only the chrome around that prose (back link, meta line, headline,
 * cover tile) is on the amp design system - `.blog-article` declares its
 * own font-family in globals.css, so the `font-plex` below stops at the
 * wrapper and never reaches CMS output. Navy is the one accent here.
 *
 * The HTML is generated by Tiptap which limits the node/mark set to a
 * known subset (paragraph, h2, h3, bold, italic, link, lists, blockquote,
 * image, code) - no script tags, no arbitrary HTML, no user-pasted
 * markup. Safe to render as-is on the server.
 */
export default function BlogArticle({ post }) {
  const date = post.published_at
    ? new Date(post.published_at).toLocaleDateString('en-IN', {
        year: 'numeric', month: 'long', day: 'numeric',
      })
    : ''

  return (
    <article className="font-plex bg-white pb-20">

      {/* Header */}
      <header className="px-5 md:px-10 pt-12 md:pt-16 max-w-3xl mx-auto">
        <Link
          href="/blog"
          className="text-[13px] font-semibold tracking-[0.08em] uppercase text-amp-caption hover:text-amp-navy transition-colors"
        >
          ← The Journal
        </Link>

        <p className="text-[11px] font-medium tracking-[0.12em] uppercase text-amp-caption mt-9 mb-4">
          {date}
          {post.author && <span className="text-amp-caption/70"> · {post.author}</span>}
        </p>

        {/* tracking-[-0.01em], not tracking-tight - the tighter -0.025em was
            out of step with every other large heading in the system. */}
        <h1 className="font-plex font-semibold text-[clamp(2.2rem,5vw,3.6rem)] leading-[1.08] tracking-[-0.01em] text-black mb-4">
          {post.title}
        </h1>

        {post.excerpt && (
          <p className="text-lg md:text-xl text-amp-body leading-relaxed mb-2">
            {post.excerpt}
          </p>
        )}
      </header>

      {/* Cover image - same column width as the header + body so the
          whole article reads as a single-column editorial layout. */}
      {post.cover_image_url && (
        <div className="mt-10 md:mt-12 px-5 md:px-10 max-w-3xl mx-auto">
          <div
            className="relative w-full overflow-hidden rounded-[16px] border border-amp-hairline"
            style={{ aspectRatio: '16/9', backgroundColor: '#f2f4f8' }}
          >
            <Image
              src={post.cover_image_url}
              alt={post.cover_image_alt || post.title}
              fill
              sizes="(max-width: 768px) 100vw, 768px"
              className="object-cover"
              priority
            />
          </div>
        </div>
      )}

      {/* Body */}
      <div className="px-5 md:px-10 mt-12 md:mt-14 max-w-3xl mx-auto">
        {post.content_html ? (
          <div
            className="blog-article"
            dangerouslySetInnerHTML={{ __html: post.content_html }}
          />
        ) : (
          <p className="text-amp-caption italic">This post has no content yet.</p>
        )}
      </div>

    </article>
  )
}
