import Link from 'next/link'
import Image from 'next/image'

/**
 * Full blog article rendering. Tiptap HTML is dropped in via
 * dangerouslySetInnerHTML; styling for the inner elements lives in
 * globals.css under the `.blog-article` namespace.
 *
 * The HTML is generated by Tiptap which limits the node/mark set to a
 * known subset (paragraph, h2, h3, bold, italic, link, lists, blockquote,
 * image, code) — no script tags, no arbitrary HTML, no user-pasted
 * markup. Safe to render as-is on the server.
 */
export default function BlogArticle({ post }) {
  const date = post.published_at
    ? new Date(post.published_at).toLocaleDateString('en-IN', {
        year: 'numeric', month: 'long', day: 'numeric',
      })
    : ''

  return (
    <article className="pb-20">

      {/* Header */}
      <header className="px-5 md:px-10 pt-12 md:pt-16 max-w-3xl mx-auto">
        <Link
          href="/blog"
          className="text-[10px] tracking-[0.2em] uppercase text-bone/40 hover:text-amber transition-colors"
        >
          ← The Journal
        </Link>

        <p className="text-[10px] tracking-[0.3em] uppercase text-bone/45 mt-9 mb-4">
          {date}
          {post.author && <span className="text-bone/30"> · {post.author}</span>}
        </p>

        <h1 className="font-display font-bold text-[clamp(2.2rem,5vw,3.6rem)] leading-[1.08] tracking-tight text-bone mb-4">
          {post.title}
        </h1>

        {post.excerpt && (
          <p className="text-lg md:text-xl text-bone/60 leading-relaxed mb-2">
            {post.excerpt}
          </p>
        )}
      </header>

      {/* Cover image — same column width as the header + body so the
          whole article reads as a single-column editorial layout. */}
      {post.cover_image_url && (
        <div className="mt-10 md:mt-12 px-5 md:px-10 max-w-3xl mx-auto">
          <div
            className="relative w-full overflow-hidden border border-bone/10"
            style={{ aspectRatio: '16/9', backgroundColor: '#E8E4DF' }}
          >
            <Image
              src={post.cover_image_url}
              alt={post.cover_image_alt || post.title}
              fill
              sizes="(max-width: 768px) 100vw, 768px"
              className="object-cover"
              priority
            />
          </div>
        </div>
      )}

      {/* Body */}
      <div className="px-5 md:px-10 mt-12 md:mt-14 max-w-3xl mx-auto">
        {post.content_html ? (
          <div
            className="blog-article"
            dangerouslySetInnerHTML={{ __html: post.content_html }}
          />
        ) : (
          <p className="text-bone/40 italic">This post has no content yet.</p>
        )}
      </div>

    </article>
  )
}
